/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_restoran.Dashboard;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import pos_restoran.DbConnection;
import pos_restoran.MenuNavigation;
import pos_restoran.UserSession;

/**
 *
 * @author User
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    private MenuNavigation menuNav;
    private Connection con;
    private Statement statment;

    public AdminDashboard() {
        initComponents();
        this.menuNav = new MenuNavigation();
        // connection DB
        DbConnection DB = new DbConnection();
        DB.Connect();
        con = DB.conn;
        statment = DB.stmt;
        String ID = UserSession.getUserLogin();
        userLogin.setText(ID);
        loadDataCount();
        loadDataCountTable();
        loadDataCountDishes();
        loadDataTotalBill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new keeptoo.KGradientPanel();
        logo2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mnOrderList = new javax.swing.JLabel();
        nmDishesList = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        mnMeja2 = new javax.swing.JLabel();
        mnDashboard4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        mnDashboard5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jumlahOrder = new javax.swing.JPanel();
        totalOrder = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jumlahOrder1 = new javax.swing.JPanel();
        remainStock = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jumlahOrder2 = new javax.swing.JPanel();
        totalDishes = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jumlahOrder3 = new javax.swing.JPanel();
        totalBill = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel3.setkEndColor(new java.awt.Color(94, 43, 22));
        kGradientPanel3.setkGradientFocus(300);
        kGradientPanel3.setkStartColor(new java.awt.Color(199, 139, 61));

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_restoran/images/smol_logo.png"))); // NOI18N

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_restoran/images/ic_order.png"))); // NOI18N

        mnOrderList.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        mnOrderList.setForeground(new java.awt.Color(255, 255, 255));
        mnOrderList.setText("Order List");
        mnOrderList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnOrderListMouseClicked(evt);
            }
        });

        nmDishesList.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nmDishesList.setForeground(new java.awt.Color(255, 255, 255));
        nmDishesList.setText("Dishes List");
        nmDishesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmDishesListMouseClicked(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_restoran/images/ic_serving-dish.png"))); // NOI18N

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_restoran/images/table.png"))); // NOI18N

        mnMeja2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        mnMeja2.setForeground(new java.awt.Color(255, 255, 255));
        mnMeja2.setText("Meja");
        mnMeja2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMejaMouseClicked(evt);
            }
        });

        mnDashboard4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        mnDashboard4.setForeground(new java.awt.Color(255, 255, 255));
        mnDashboard4.setText("Logout");
        mnDashboard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDashboard2MouseClicked(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_restoran/images/ic_logout.png"))); // NOI18N

        mnDashboard5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        mnDashboard5.setForeground(new java.awt.Color(255, 255, 255));
        mnDashboard5.setText("Dashboard");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_restoran/images/ic_home_blong.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo2)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mnMeja2))
                    .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(mnDashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel3Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(mnOrderList))
                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nmDishesList))
                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mnDashboard5))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo2)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(mnDashboard5))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(mnOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(nmDishesList))
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel21))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mnMeja2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mnDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setText("Dashboard");

        jumlahOrder.setBackground(new java.awt.Color(255, 255, 255));
        jumlahOrder.setPreferredSize(new java.awt.Dimension(200, 200));
        jumlahOrder.setLayout(new java.awt.BorderLayout());

        totalOrder.setFont(new java.awt.Font("Calibri", 0, 80)); // NOI18N
        totalOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalOrder.setText("10");
        jumlahOrder.add(totalOrder, java.awt.BorderLayout.CENTER);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total Order");
        jumlahOrder.add(jLabel15, java.awt.BorderLayout.PAGE_END);

        jumlahOrder1.setBackground(new java.awt.Color(255, 255, 255));
        jumlahOrder1.setPreferredSize(new java.awt.Dimension(200, 200));
        jumlahOrder1.setLayout(new java.awt.BorderLayout());

        remainStock.setFont(new java.awt.Font("Calibri", 0, 80)); // NOI18N
        remainStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remainStock.setText("10");
        jumlahOrder1.add(remainStock, java.awt.BorderLayout.CENTER);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Meja");
        jumlahOrder1.add(jLabel14, java.awt.BorderLayout.PAGE_END);

        jumlahOrder2.setBackground(new java.awt.Color(255, 255, 255));
        jumlahOrder2.setPreferredSize(new java.awt.Dimension(200, 200));
        jumlahOrder2.setLayout(new java.awt.BorderLayout());

        totalDishes.setFont(new java.awt.Font("Calibri", 0, 80)); // NOI18N
        totalDishes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalDishes.setText("20");
        jumlahOrder2.add(totalDishes, java.awt.BorderLayout.CENTER);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total Dishes");
        jumlahOrder2.add(jLabel13, java.awt.BorderLayout.PAGE_END);

        jumlahOrder3.setBackground(new java.awt.Color(255, 255, 255));
        jumlahOrder3.setPreferredSize(new java.awt.Dimension(200, 200));
        jumlahOrder3.setLayout(new java.awt.GridLayout(1, 0));

        totalBill.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        totalBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBill.setText("Rp.120000");
        jumlahOrder3.add(totalBill);

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Total Bill");
        jumlahOrder3.add(jLabel17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_restoran/images/ic_user.png"))); // NOI18N

        userLogin.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jumlahOrder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlahOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addComponent(jumlahOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLogin)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userLogin)
                        .addComponent(jLabel2)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jumlahOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jumlahOrder3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
        );

        jumlahOrder.getAccessibleContext().setAccessibleName("");
        jumlahOrder.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnDashboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDashboard2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logout Berhasil");
        menuNav.loginPage(this);
    }//GEN-LAST:event_mnDashboard2MouseClicked

    private void mnMejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMejaMouseClicked
        menuNav.mejaList(this);
    }//GEN-LAST:event_mnMejaMouseClicked

    private void nmDishesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmDishesListMouseClicked
        this.menuNav.dishList(this);
    }//GEN-LAST:event_nmDishesListMouseClicked

    private void mnOrderListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnOrderListMouseClicked
        // TODO add your handling code here:
        menuNav.orderList(this);
    }//GEN-LAST:event_mnOrderListMouseClicked
    private void loadDataCount() {
        try {

            String selectQuery = "SELECT *, Count(*) as count FROM pembayaran";
            ResultSet result = statment.executeQuery(selectQuery);
            while (result.next()) {
                if (result.getString("count") != null) {

                    totalOrder.setText(result.getString("count"));
                } else {
                    totalOrder.setText("0");
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            System.err.println(ex.getMessage());
        }
    }

    private void loadDataCountDishes() {
        try {

            String selectQuery = "SELECT *, Count(*) as count FROM menu";
            ResultSet result = statment.executeQuery(selectQuery);
            while (result.next()) {
                if (result.getString("count") != null) {

                    totalDishes.setText(result.getString("count"));
                } else {
                    totalOrder.setText("0");
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            System.err.println(ex.getMessage());
        }
    }

    private void loadDataCountTable() {
        try {

            String selectQuery = "SELECT *, Count(*) as count FROM meja";
            ResultSet result = statment.executeQuery(selectQuery);
            while (result.next()) {
                if (result.getString("count") != null) {

                    remainStock.setText(result.getString("count"));

                } else {
                    totalOrder.setText("0");
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            System.err.println(ex.getMessage());
        }
    }

    private void loadDataTotalBill() {
        try {

            String selectQuery = "SELECT *, SUM(sub_total) as total FROM pembayaran";
            ResultSet result = statment.executeQuery(selectQuery);
            while (result.next()) {
                if (result.getString("total") != null) {

                    totalBill.setText("Rp. " + result.getString("total") + ",-");

                } else {
                    totalOrder.setText("0");
                }
                //System.out.println(result.getString("total"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            System.err.println(ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jumlahOrder;
    private javax.swing.JPanel jumlahOrder1;
    private javax.swing.JPanel jumlahOrder2;
    private javax.swing.JPanel jumlahOrder3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel mnDashboard;
    private javax.swing.JLabel mnDashboard1;
    private javax.swing.JLabel mnDashboard2;
    private javax.swing.JLabel mnDashboard3;
    private javax.swing.JLabel mnDashboard4;
    private javax.swing.JLabel mnDashboard5;
    private javax.swing.JLabel mnDishes;
    private javax.swing.JLabel mnDishes1;
    private javax.swing.JLabel mnMeja;
    private javax.swing.JLabel mnMeja1;
    private javax.swing.JLabel mnMeja2;
    private javax.swing.JLabel mnOrderList;
    private javax.swing.JLabel nmDishesList;
    private javax.swing.JLabel remainStock;
    private javax.swing.JLabel totalBill;
    private javax.swing.JLabel totalDishes;
    private javax.swing.JLabel totalOrder;
    private javax.swing.JLabel userLogin;
    // End of variables declaration//GEN-END:variables
}
